### ISSUE TITLE
UnicodeDecodeError when pasting content from "foreign" site to richtext-tile

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#357]
A client of mine is moving content to their new site by copy-pasting the html over in source mode of tinymce. 

Some characters are causing the richtext-tile to throw an UnicodeDecodeError.

```
2017-05-02 15:46:36 ERROR plone.subrequest Error handling subrequest to http://localhost:12980/Plone/de/test2/@@plone.app.standardtiles.html/976e9657-369f-4e40-9d2a-1bd4ab7d4319
Traceback (most recent call last):
  File "/Users/peter/workspace/mosaictest/eggs/plone.subrequest-1.8-py2.7.egg/plone/subrequest/__init__.py", line 154, in subrequest
    bind=1
  File "/Users/peter/workspace/mosaictest/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/Users/peter/workspace/mosaictest/eggs/plone.app.standardtiles-2.1.0-py2.7.egg/plone/app/standardtiles/html.py", line 40, in __call__
    return u"<html><body>%s</body></html>" % content
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 63: ordinal not in range(128)

```

What is the correct way to fix this or how do we want it to be handled?

**Comment by agitator** [comment]
the field tile for the richtext-behavior handles it correctly

**Comment by datakurre** [comment]
This should be fixed already at master by

**Comment by datakurre** [comment]
https://github.com/plone/plone.app.standardtiles/commit/232dc154d0cd804a6f1de99af6224ae86d4951c4

**Comment by agitator** [comment]
yes, that solves it!

have you got time for a release?

**Comment by agitator** [comment]
fixed in https://github.com/plone/plone.app.standardtiles/commit/232dc154d0cd804a6f1de99af6224ae86d4951c4
