### ISSUE TITLE
Unable to add image within RichText tile

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.mosaic#365]
plone.app.mosaic 2.0rc5
Plone 5.1b3

I added a RichText title and tried to add an existing image inside the tile...fails with:

```

plone-logged-in-compiled.min.js:5 Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.
    at j.setRng (http://dev.zopyx.de:12020/Plone5/++plone++static/++unique++2017-04-04%2012%3A20%3A52.676966/plone-logged-in-compiled.min.js:5:14507)
    at j.select (http://dev.zopyx.de:12020/Plone5/++plone++static/++unique++2017-04-04%2012%3A20%3A52.676966/plone-logged-in-compiled.min.js:5:12283)
    at d.focusElement (http://dev.zopyx.de:12020/Plone5/++plone++static/++unique++2017-04-04%2012%3A20%3A52.676966/plone-logged-in-compiled.min.js:15:19971)
    at HTMLImageElement.a.onload.a.onerror (http://dev.zopyx.de:12020/Plone5/++plone++static/++unique++2017-04-04%2012%3A20%3A52.676966/plone-logged-in-compiled.min.js:15:20100)
```
```

**Comment by tomgross** [comment]
Duplicate #352

**Comment by jensens** [comment]
With latest mosaic this is no longer a problem. I used it recently a lot. Tested both, existing image and freshly upload.
![screenshot from 2017-11-24 11 52 44](https://user-images.githubusercontent.com/157140/33207448-0a07faa8-d10e-11e7-93fd-8ac053676058.png)
