### ISSUE TITLE
Mosaic pages render empty

### ISSUE THREAD

**Issue by ksuess** [plone/plone.app.mosaic#480]
**Steps to reproduce**
1. Change view of page to 'Mosaic'
2. See an empty page

**Software**
Plone 5.2.4
Python 3.8.7
Mosaic 2.2.3

```
2021-04-15 10:00:47,863 ERROR   [plone.transformchain:69][waitress-0] Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/Users/someone/Plone/somethingch/somethingdeployment2020/work/eggs/plone.transformchain-2.0.2-py3.8.egg/plone/transformchain/transformer.py", line 59, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/Users/someone/Plone/somethingch/somethingdeployment2020/work/eggs/plone.app.blocks-4.3.2-py3.8.egg/plone/app/blocks/transform.py", line 91, in transformIterable
    result = getHTMLSerializer(
  File "/Users/someone/Plone/somethingch/somethingdeployment2020/work/eggs/repoze.xmliter-0.6-py3.8.egg/repoze/xmliter/utils.py", line 26, in getHTMLSerializer
    serializer = getXMLSerializer(
  File "/Users/someone/Plone/somethingch/somethingdeployment2020/work/eggs/repoze.xmliter-0.6-py3.8.egg/repoze/xmliter/utils.py", line 16, in getXMLSerializer
    p.feed(chunk)
  File "src/lxml/parser.pxi", line 1256, in lxml.etree._FeedParser.feed
  File "src/lxml/parser.pxi", line 1291, in lxml.etree._FeedParser.feed
lxml.etree.ParserError: Unicode parsing is not supported on this platform
```

**Comment by ksuess** [comment]
Fixed by https://github.com/plone/plone.app.blocks/pull/85
